import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { FiAlertTriangle, FiDownload } from 'react-icons/fi';
import ReportCard from '../../components/common/ReportCard';
import { printReportCards } from '../../utils/printHelper';
import api from '../../services/api';

export default function SharedResult() {
  const { token } = useParams();
  const [data, setData]       = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState('');

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const res = await api.get(`/results/share-data/${token}`);
        setData(res.data);
      } catch (err) {
        setError(
          err?.response?.data?.message ||
          'This result link has expired or is invalid.'
        );
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [token]);

  const handlePrint = () => {
    if (!data) return;
    printReportCards([{
      student:  data.student,
      results:  data.data || [],
      summary:  data.summary,
      term:     data.term,
      session:  data.session,
    }]);
  };

  // ── Error state ─────────────────────────────────────────────────────────────
  if (!loading && error) {
    return (
      <div className="min-h-screen bg-secondary-50 flex items-center justify-center p-6">
        <div className="card max-w-md w-full text-center space-y-4">
          <FiAlertTriangle size={40} className="mx-auto text-amber-500" />
          <h1 className="text-xl font-bold text-secondary-800">Link Expired or Invalid</h1>
          <p className="text-sm text-secondary-500">{error}</p>
          <Link to="/" className="btn-secondary text-sm inline-block">← Back to Home</Link>
        </div>
      </div>
    );
  }

  // ── Header bar ──────────────────────────────────────────────────────────────
  const termLabel = data?.term
    ? data.term.charAt(0).toUpperCase() + data.term.slice(1) + ' Term'
    : '';

  return (
    <div className="min-h-screen bg-secondary-50">
      {/* Top bar */}
      <div className="bg-white border-b border-secondary-100 px-6 py-4 flex items-center justify-between sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-primary-500 flex items-center justify-center">
            <span className="text-white font-bold text-sm">S</span>
          </div>
          <div>
            <p className="font-semibold text-secondary-800 text-sm">SmartSchool</p>
            <p className="text-xs text-secondary-400">Shared Academic Result</p>
          </div>
        </div>
        {data && (
          <div className="flex items-center gap-3">
            <span className="hidden sm:inline text-xs text-secondary-500 bg-secondary-100 px-3 py-1.5 rounded-full">
              {termLabel} · {data.session}
            </span>
            <button
              onClick={handlePrint}
              className="btn-secondary text-sm flex items-center gap-2"
            >
              <FiDownload size={14} /> Print / Save PDF
            </button>
          </div>
        )}
      </div>

      {/* Report card */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <ReportCard
          student={data?.student}
          results={data?.data || []}
          summary={data?.summary}
          term={data?.term}
          session={data?.session}
          loading={loading}
        />

        {!loading && (
          <p className="text-center text-xs text-secondary-400 mt-8">
            Generated by SmartSchool Management System ·{' '}
            <Link to="/" className="underline hover:text-secondary-600">Visit SmartSchool</Link>
          </p>
        )}
      </div>
    </div>
  );
}
